server:
  port: 8100

spring:
  application:
    name: zuul-server # 应用名称
  servlet:
    multipart:
      max-file-size: 200MB #单个文件上传大小
      max-request-size: 600MB #连续上传文件大小
      location: / #临时目录

# 服务注册与发现
eureka:
  client:
    service-url:
      # 服务注册地址
      defaultZone: http://peer1:10081/eureka/,http://peer2:10082/eureka/,http://peer3:10083/eureka/
  instance:
    prefer-ip-address: true

# 路由转发
zuul:
  routes:
    zuul-client:
      path: /api/**
      serviceId: zuul-client

# hystrix 超时设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
# ribbon 超时设置
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

# 端点管理
management:
  endpoints:
    web:
      exposure:
        include: routes,filters

